<?php

namespace xqwtxon\SlapperRotationV2;

interface SlapperRotationInfo {
    /**
     * NOTE FOR DEVELOPERS:
     * CHANGING THIS COULD BREAK THIS PLUGIN!
     * 
     * SUBMITTING PULL REQUEST TO CHANGE THIS PLUGIN COMPATIBLE VERSION WILL AUTOMATICALLY CLOSED!
     * YOU ARE WASTING TIME FOR MODIFYING THIS!
     * 
     * THIS FILE WAS AUTO-GENERATED BY PLUGIN!
    **/
    const PLUGIN_NAME = "SlapperParticlesV2";
    const BRANCH = "main";
    const PLUGIN_DESCRIPTION = "Slappers will now have particles!";
    const MAIN = "Main";
    const CONFIG_VERSION = "1.0.0";
    const POCKETMINE_VERSION = "4.2.6";
    const PROTOCOL_VERSION = 486;
    const PLUGIN_VERSION = "2.0.0";
    const VERSION = "v2.0.0";
    const DEFAULT_COLOR_A = 255;
    const DEFAULT_COLOR_B = 255;
    const DEFAULT_COLOR_C = 255;
    const IS_DEVELOPMENT_BUILD = false;
}